# Generated by Django 5.0.6 on 2024-06-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='u_id',
            field=models.IntegerField(default=1),
        ),
    ]
