# Generated by Django 5.0.6 on 2024-07-01 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_productsmodel_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsmodel',
            name='product_id',
        ),
    ]
