# Generated by Django 5.0.6 on 2024-07-02 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_alter_order_customer_email_alter_order_customer_name_and_more'),
        ('seller', '0005_remove_productsmodel_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.productsmodel')),
            ],
        ),
    ]
